"""The two motor-mount parts -- the bottom-most layer of the chassis,
below the battery box, one per side. Both sides share this one parametric
definition; the left half is generated by mirroring the right half about
the chassis centerline (Y = CHASSIS_WIDTH / 2), so there is exactly one
geometry definition to get right.

Each half is an L-shaped bracket:
  - a horizontal FOOT, spanning the full chassis length (X) and half the
    chassis width (Y) -- same role as before: inner-seam bolt row joining
    it to the other half, standoff bosses on top for the battery box.
  - a vertical RAIL rising from the foot's outer edge (Y = half_W), which
    the TT motor bolts flush against from the inside. The motor's real
    shaft passes straight through a clearance hole in this rail (not off
    a plate edge) -- see params.py's Motors section for why: the vendor
    STEP file (TTMotorDualShaft.stp) shows this is a flat-face-down mount
    with 2 real M3 bolts straddling the shaft, not 4 bolts around a
    pocket. The wheel attaches to the shaft on the rail's outside face.

PLACEHOLDER geometry: rail height/thickness/length are first-draft
assumptions (the shaft's height above the foot is derived from
WHEEL_DIAMETER, see params.RAIL_SHAFT_Z) -- see params.py for what still
needs real measurements. The seam bolt count is also a first-draft
assumption.
"""

from typing import Any, List, Tuple
import FreeCAD as App
import Part
import common
import params as P

SEAM_BOLT_COUNT = 3  # PLACEHOLDER -- number of bolts joining the two halves along the centerline seam


def _cut_holes_along_y(shape: Any, positions_xz: List[Tuple[float, float]], diameter: float, y0: float, depth: float) -> Any:
    """Cut a round hole bored along Y (not Z, unlike common.cut_through_holes)
    at each (x, z) in positions_xz, spanning y0 .. y0+depth with a little
    overrun on both ends for a clean through-cut -- used for the rail's
    shaft/bolt holes, which pass through its Y-thickness."""
    result = shape
    for x, z in positions_xz:
        hole = Part.makeCylinder(
            diameter / 2.0, depth + 2.0, App.Vector(x, y0 - 1.0, z), App.Vector(0, 1, 0)
        )
        result = result.cut(hole)
    return result


class MotorMount(common.ParametricPart):
    def add_properties(self, obj: Any) -> None:
        obj.addProperty(
            "App::PropertyEnumeration", "Side", "Chassis", "Which half of the chassis this part is"
        )
        obj.Side = ["right", "left"]
        obj.Side = "right"

        obj.addProperty("App::PropertyLength", "Length", "Chassis", "Chassis length (X)").Length = P.CHASSIS_LENGTH
        obj.addProperty("App::PropertyLength", "Width", "Chassis", "Full chassis width (Y) -- this part spans half of it").Width = P.CHASSIS_WIDTH
        obj.addProperty("App::PropertyLength", "Thickness", "Chassis", "Foot thickness").Thickness = P.MOTOR_MOUNT_THICKNESS
        obj.addProperty("App::PropertyLength", "CornerRadius", "Chassis", "Outer corner rounding").CornerRadius = P.CORNER_RADIUS

        obj.addProperty("App::PropertyLength", "BoltHoleDiameter", "Assembly", "Clearance hole diameter for M3 bolts").BoltHoleDiameter = P.BOLT_DIAMETER
        obj.addProperty("App::PropertyLength", "StandoffOuterDiameter", "Assembly", "Standoff boss diameter").StandoffOuterDiameter = P.STANDOFF_OUTER_DIAMETER
        obj.addProperty("App::PropertyLength", "StandoffHeight", "Assembly", "Gap to the battery box above").StandoffHeight = P.STANDOFF_HEIGHT
        # Note: the 4 corner assembly-bolt positions are intentionally NOT
        # exposed as an editable property here -- they come straight from
        # params.assembly_bolt_positions() so this part, battery_box.py and
        # top_plate.py can never drift out of physical alignment with each
        # other. Change ASSEMBLY_BOLT_INSET in params.py, not per-part.

        obj.addProperty("App::PropertyLength", "RailThickness", "Motor", "Vertical bracket rail thickness").RailThickness = P.RAIL_THICKNESS
        obj.addProperty("App::PropertyLength", "RailHeight", "Motor", "Vertical bracket rail height above the foot").RailHeight = P.RAIL_HEIGHT
        obj.addProperty("App::PropertyLength", "RailLengthX", "Motor", "Rail width along the chassis-length axis").RailLengthX = P.RAIL_LENGTH_X
        obj.addProperty("App::PropertyLength", "ShaftZ", "Motor", "Shaft height above the foot's top face").ShaftZ = P.RAIL_SHAFT_Z
        obj.addProperty("App::PropertyLength", "ShaftClearance", "Motor", "Shaft clearance-hole diameter through the rail").ShaftClearance = P.MOTOR_SHAFT_CLEARANCE
        obj.addProperty("App::PropertyLength", "MotorBoltHoleSpacing", "Motor", "Spacing between the 2 real motor bolt holes").MotorBoltHoleSpacing = P.MOTOR_BOLT_HOLE_SPACING
        obj.addProperty("App::PropertyLength", "MotorBoltToShaftOffset", "Motor", "Distance from shaft center to the bolt-hole row").MotorBoltToShaftOffset = P.MOTOR_BOLT_TO_SHAFT_OFFSET
        obj.addProperty("App::PropertyLength", "MotorBoltHoleDiameter", "Motor", "Motor bolt clearance-hole diameter").MotorBoltHoleDiameter = P.MOTOR_BOLT_HOLE_DIAMETER

    def build_shape(self, obj: Any) -> Any:
        L = obj.Length.Value
        full_W = obj.Width.Value
        half_W = full_W / 2.0
        T = obj.Thickness.Value

        foot = common.rounded_plate(L, half_W, T, obj.CornerRadius.Value)

        # Vertical bracket rail, flush with the outer edge (Y = half_W),
        # rising from the top of the foot. The motor's flat mounting face
        # bolts against this rail's inside face; its shaft passes through
        # a clearance hole to the wheel on the outside. See module
        # docstring and params.py's Motors section for why this replaced
        # the earlier pocket-in-a-flat-plate design.
        motor_center_x = L * 0.75
        rail_x0 = motor_center_x - obj.RailLengthX.Value / 2.0
        rail_y0 = half_W - obj.RailThickness.Value
        rail = Part.makeBox(
            obj.RailLengthX.Value, obj.RailThickness.Value, obj.RailHeight.Value,
            App.Vector(rail_x0, rail_y0, T),
        )
        plate = foot.fuse(rail)

        # Shaft clearance hole, centered on the rail at its designed height.
        shaft_z = T + obj.ShaftZ.Value
        plate = _cut_holes_along_y(
            plate, [(motor_center_x, shaft_z)], obj.ShaftClearance.Value, rail_y0, obj.RailThickness.Value,
        )

        # The 2 real motor mounting bolts, straddling the shaft's X position,
        # offset below it by the confirmed shaft-to-bolt-row distance (the
        # motor body/can hangs down toward the foot on this side).
        hb = obj.MotorBoltHoleSpacing.Value / 2.0
        bolt_z = shaft_z - obj.MotorBoltToShaftOffset.Value
        bolt_holes = [(motor_center_x - hb, bolt_z), (motor_center_x + hb, bolt_z)]
        plate = _cut_holes_along_y(
            plate, bolt_holes, obj.MotorBoltHoleDiameter.Value, rail_y0, obj.RailThickness.Value,
        )

        # Inner-seam bolt row (Y = 0), joining this half to the other one.
        seam_holes = [
            (L * (i + 1) / (SEAM_BOLT_COUNT + 1), 0.0) for i in range(SEAM_BOLT_COUNT)
        ]
        plate = common.cut_through_holes(plate, seam_holes, obj.BoltHoleDiameter.Value, 0, T)

        # Standoffs for the battery box above, at whichever whole-chassis
        # assembly-bolt corners fall within this half's footprint.
        all_positions = P.assembly_bolt_positions()
        # assembly_bolt_positions() is expressed over the FULL chassis
        # width; this half only ever spans Y in [half_W, full_W] before
        # mirroring (see build() below), so filter against that range.
        half_positions = common.positions_within(all_positions, 0, L, half_W, full_W)
        # Re-express in this part's own local frame (Y measured from the seam).
        local_positions = [(x, y - half_W) for x, y in half_positions]
        standoffs = common.standoff_bosses(
            local_positions, T, obj.StandoffHeight.Value,
            obj.StandoffOuterDiameter.Value, obj.BoltHoleDiameter.Value,
        )
        if standoffs is not None:
            plate = plate.fuse(standoffs)

        if obj.Side == "left":
            plate = plate.mirror(App.Vector(0, 0, 0), App.Vector(0, 1, 0))

        return plate


def build(doc: Any, side: str = "right") -> Any:
    obj = doc.addObject("Part::FeaturePython", "MotorMount" + side.capitalize())
    MotorMount(obj)
    obj.Side = side
    return obj
